place CELL
place CYTOPLASM in the CELL
place LYSOSOME in the CELL
stable DAMAGED-MEMBRANE in the LYSOSOME
stable JUNK-PROTEIN in the CYTOPLASM
stable JUNK-PROTEIN in the LYSOSOME
stable LIPOFUSCIN in the CYTOPLASM
stable LIPOFUSCIN in the LYSOSOME
stable OXIDIZED-PROTEIN in the LYSOSOME
transient FE in the LYSOSOME
transient H2O2 in the CYTOPLASM
transient H2O2 in the LYSOSOME
transient ROS in the LYSOSOME
transient DEGRADATION-RATE in the LYSOSOME
transient LYTIC-ENZYME in the LYSOSOME
claim FE in the LYSOSOME INCREASES with JUNK-PROTEIN in the CYTOPLASM
claim H2O2 in the LYSOSOME INCREASES with H2O2 in the CYTOPLASM
claim ROS in the LYSOSOME INCREASES with FE in the LYSOSOME
claim ROS in the LYSOSOME INCREASES with LIPOFUSCIN in the LYSOSOME
claim DAMAGED-MEMBRANE in the LYSOSOME INCREASES with ROS in the LYSOSOME
claim DEGRADATION-RATE in the LYSOSOME DECREASES with LIPOFUSCIN in the LYSOSOME
claim JUNK-PROTEIN in the CYTOPLASM DECREASES with DEGRADATION-RATE in the LYSOSOME
claim JUNK-PROTEIN in the CYTOPLASM INCREASES with JUNK-PROTEIN in the LYSOSOME
claim LIPOFUSCIN in the LYSOSOME INCREASES with OXIDIZED-PROTEIN in the LYSOSOME
claim LIPOFUSCIN in the CYTOPLASM INCREASES with DAMAGED-MEMBRANE in the LYSOSOME
claim LYTIC-ENZYME in the LYSOSOME DECREASES with LIPOFUSCIN in the LYSOSOME
claim OXIDIZED-PROTEIN in the LYSOSOME INCREASES with ROS in the LYSOSOME
fact LYTIC-ENZYME in the LYSOSOME DECREASES with ROS in the LYSOSOME
fact H2O2 in the LYSOSOME DOES-NOT-CHANGE with ROS in the LYSOSOME
fact LIPOFUSCIN in the LYSOSOME INCREASES with TIME
fact LIPOFUSCIN in the CYTOPLASM INCREASES with TIME
done