
place CELL
place LYSOSOME in the CELL
place CYTOPLASM in the CELL
place CHLOROPLAST in the CELL
STABLE JUNK-PROTEIN in the LYSOSOME
STABLE JUNK-PROTEIN in the CYTOPLASM
TRANSIENT DEGRADATION-RATE in the LYSOSOME
TRANSIENT FE in the LYSOSOME
TRANSIENT ROS in the LYSOSOME
STABLE OXIDIZED-PROTEIN in the LYSOSOME
STABLE LIPOFUSCIN in the LYSOSOME
STABLE LIPOFUSCIN in the CYTOPLASM
TRANSIENT LYTIC-ENZYME in the LYSOSOME
STABLE DAMAGED-MEMBRANE in the LYSOSOME
TRANSIENT H2O2 in the LYSOSOME
TRANSIENT H2O2 in the CYTOPLASM
claim JUNK-PROTEIN DECREASES with DEGRADATION-RATE in the LYSOSOME
claim JUNK-PROTEIN in the LYSOSOME INCREASES with JUNK-PROTEIN in the CYTOPLASM
note LAMP2A IMPORTS JUNK-PROTEIN PROTEINS FROM CYTOPLASM INTO LYSOSOME
claim FE INCREASES with JUNK-PROTEIN in the LYSOSOME
note LYSOSOME DIGESTION PRODUCES FE FROM JUNK PROTEINS
claim ROS INCREASES with FE in the LYSOSOME
note FREE FE REACTS WITH H2O2 TO PRODUCE ROS
claim OXIDIZED-PROTEIN INCREASES with ROS in the LYSOSOME
note ROS OXIDIZES PROTEINS TO PRODUCE OXIDIZED PROTEINS
claim LIPOFUSCIN INCREASES with OXIDIZED-PROTEIN in the LYSOSOME
note OXIDIZED-PROTEINS AND FE CROSSLINK TO FORM LIPOFUSCIN
claim DEGRADATION-RATE DECREASES with LIPOFUSCIN in the LYSOSOME
note LIPOFUSCIN REDUCES THE RATE OF DISASSEMBLING JUNK PROTEINS
claim LYTIC-ENZYME DECREASES with LIPOFUSCIN in the LYSOSOME
note LIPOFUSCIN-FILLED LYSOSOMES REQUIRE MORE LYTIC ENZYMES
claim ROS INCREASES with LIPOFUSCIN in the LYSOSOME
note FE IN LIPOFUSCIN REACTS WITH H2O2 TO PRODUCE ROS
claim DAMAGED-MEMBRANE INCREASES with ROS in the LYSOSOME
note ROS IN LYSOSOMES DAMAGES LYSOSOMAL MEMBRANES
claim LIPOFUSCIN in the CYTOPLASM INCREASES with DAMAGED-MEMBRANE in the LYSOSOME
note DAMAGED LYSOSOMAL MEMBRANES SPILL LIPOFUSCIN INTO CYTOPLASM
claim H2O2 in the LYSOSOME INCREASES with H2O2 in the CYTOPLASM
note H2O2 FROM CYTOPLASM DIFFUSES INTO THE LYSOSOME
fact LIPOFUSCIN in the LYSOSOME INCREASES with TIME
fact LIPOFUSCIN in the CYTOPLASM INCREASES with TIME
fact LYTIC-ENZYME DECREASES with ROS in the LYSOSOME
fact H2O2 DOES-NOT-CHANGE with ROS in the LYSOSOME
done
